/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 .\earth.glb --transform 
Files: .\earth.glb [23.34MB] > earth-transformed.glb [1.02MB] (96%)
Author: SebastianSosnowski (https://sketchfab.com/SebastianSosnowski)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-4de1bcbd22a444abb4f089b9b78ec96a
Title: Earth
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/earth-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode">
          <group name="Earth" rotation={[-Math.PI / 2, 0, 0]}>
            <mesh name="Earth_Material_#50_0" geometry={nodes['Earth_Material_#50_0'].geometry} material={materials.Material_50} />
          </group>
          <group name="EarthClouds" rotation={[-Math.PI / 2, -Math.PI / 9, 0]} scale={1.01}>
            <mesh name="EarthClouds_Material_#62_0" geometry={nodes['EarthClouds_Material_#62_0'].geometry} material={materials.Material_62} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/earth-transformed.glb')
