/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 .\man.glb --transform 
Files: .\man.glb [561.67KB] > man-transformed.glb [64.69KB] (88%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/man-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.copy.geometry} material={materials.phong1} position={[0.012, -0.002, 0.007]} rotation={[Math.PI / 2, 0, -1.502]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/man-transformed.glb')
